## Evaluación de NumPy Mónica Serrano

1. Importa la librería de NumPy.

In [146]:
import numpy as np

2. Crea un array de 1 dimension y 10 elementos.

Como no especifica si la array tiene que ser de numeros enteros o decimales, vamos a utilizar diferentes métodos.

In [147]:
# Método 1
array1_1 = np.random.randint (0,100,(10))
array1_1

array([95, 70, 84, 80, 67, 77, 67, 68, 96, 54])

In [148]:
# Método 2
array1_2 = np.random.random_sample(10).round(1) # También se podría hacer np.round(np.random.random_sample(10),1)
array1_2

array([0.3, 0.1, 0.2, 0.2, 0.2, 0.3, 0.1, 0.6, 1. , 0.7])

3. Reemplaza todos los números impares por el valor "impar" y los pares por "par". Para hacer esto os tendréis que crear un array nuevo donde vayáis añadiendo los valores nuevos

Primero vamos a utilizar un array que tenga números enteros. Lo recordamos y vemos el resultado final:

In [149]:
array1_1

array([95, 70, 84, 80, 67, 77, 67, 68, 96, 54])

In [150]:
array_par_impar= np.where(array1_1 % 2 == 0 , 'par', 'impar')
array_par_impar

array(['impar', 'par', 'par', 'par', 'impar', 'impar', 'impar', 'par',
       'par', 'par'], dtype='<U5')

In [151]:
# El array original se mantiene intacto.
array1_1

array([95, 70, 84, 80, 67, 77, 67, 68, 96, 54])

Ahora lo hacemos para una array que tenga decimales, lo cual varía un poco el código.

In [152]:
array1_2

array([0.3, 0.1, 0.2, 0.2, 0.2, 0.3, 0.1, 0.6, 1. , 0.7])

In [153]:
array_final = array1_2 * 10 # Lo multiplicamos por 10 para poder hacer el cálculo correctamente.
array_final = np.where(array_final % 2 == 0 , 'par', 'impar')
array_final

array(['impar', 'impar', 'par', 'par', 'par', 'impar', 'impar', 'par',
       'par', 'impar'], dtype='<U5')

También se podría hacer un bucle que pase por cada elemento y añada la palabra a un array vacío.

In [154]:
array_vacio = np.empty(10,dtype=object)
for indice in range(array1_1.shape[0]):
    if array1_1[indice] % 2 == 0:
        array_vacio[indice] = 'par'
    else:
        array_vacio[indice] = 'impar'

In [155]:
array_vacio

array(['impar', 'par', 'par', 'par', 'impar', 'impar', 'impar', 'par',
       'par', 'par'], dtype=object)

4. Cambiad la forma del array del ejercicio 3 a un array de 2 filas y 5 columnas.

In [156]:
array_par_impar = array_par_impar.reshape(2,5) # El primer numero son las filas y el segundo las columnas.
array_par_impar


array([['impar', 'par', 'par', 'par', 'impar'],
       ['impar', 'impar', 'par', 'par', 'par']], dtype='<U5')

5. Extrae los elementos comunes de los siguientes arrays

In [157]:
array1 = np.array([1,2,3,2,3,4,3,4,5,6])
array2 = np.array([7,2,10,2,7,4,9,4,9,8])

In [158]:
elementos_comunes = np.intersect1d(array1,array2)
# Podemos ponerle un return indices, donde también extraerá sus indices en el array1 y en el array2.
elementos_comunes = np.intersect1d(array1,array2,return_indices=True)
elementos_comunes

(array([2, 4]), array([1, 5]), array([1, 5]))

6. Extraed los elementos que están en el array1 pero no en el array2.

In [159]:
elementos_diferentes = np.setdiff1d(array1,array2)
elementos_diferentes

array([1, 3, 5, 6])

7. Extraed las posiciones donde tengamos elementos que sean iguales.

Recordarmos los arrays:

In [160]:
print(f'El array1 es {array1}')
print(f'El array2 es {array2}')

El array1 es [1 2 3 2 3 4 3 4 5 6]
El array2 es [ 7  2 10  2  7  4  9  4  9  8]


In [161]:
posiciones = np.where(array1 == array2)[0]
posiciones

array([1, 3, 5, 7])

In [162]:
# Podemos saber los numeros que son, interando por el resultado anterior y sacando los numeros
for i in posiciones:
    print(f'El número que se encuentra en posición {i} es {array1[i]}')

El número que se encuentra en posición 1 es 2
El número que se encuentra en posición 3 es 2
El número que se encuentra en posición 5 es 4
El número que se encuentra en posición 7 es 4


8. Cread un array de 3 filas y 5 columnas, con números enteros del 0 al 50. Una vez creado, extrae los valores que sean menores que 10 y mayores que 40.

In [163]:
array3 = np.random.randint(0,50,(3,5))
array3

array([[24, 11, 27, 22, 26],
       [16, 25, 29,  7, 14],
       [33, 14, 46, 29,  5]])

In [164]:
cond1 = array3 < 10
cond2 = array3 > 40

In [165]:
# Como nos dicen los valores que sea menor que 10 y mayor de 40, ponemos &.
resultado = array3[cond1 & cond2]
resultado

array([], dtype=int64)

Vemos que no nos sale ningún valor, esto tiene sentido porque realmente no hay ningun mayor 40 y menor de 10. Si quisieramos que nos saliesen valores, tendríamos que usar el comando | (or), para que nos de los numeros menores de 10 o mayores de 40.

In [166]:
resultado = array3[cond1 | cond2]
resultado

array([ 7, 46,  5])

9. Cread un array de 5x3 con números decimales aleatorios entre el 5 y el 10.

In [167]:
array4 = np.random.uniform(5,10,(5,3)).round(2)
array4

array([[7.7 , 9.44, 7.16],
       [9.39, 9.18, 8.62],
       [6.18, 8.72, 9.95],
       [8.07, 9.38, 7.18],
       [7.05, 7.64, 9.13]])

10. Crea un array de tres dimensiones de 2x4x7 con números entre el 1 y el 20
    * Transponed el array para que tenga 4 matrices, 7 filas y 2 columnas

In [168]:
array5 = np.random.randint(1,20,(2,4,7))
print(array5)

[[[13  3  4 18 16 19 16]
  [ 5  2  9  7  5  1  8]
  [11  9 14  5 16 12  2]
  [ 4  7 19  5  7 18  6]]

 [[11 19  6  4 16  8  8]
  [ 8 13  8 12  1  9 11]
  [ 1 12 12  6 12 13 19]
  [17  4  2 15 14 12 16]]]


In [169]:
''' El método transpose cambia la forma del array pero tenemos que especificar que valor queremos cambiar de nº de filas(1), columnas(2) o matrices(0), 
intercambiandose entre ellas.'''
array5_cambiado = np.transpose(array5,(1,2,0))
print(array5_cambiado)

[[[13 11]
  [ 3 19]
  [ 4  6]
  [18  4]
  [16 16]
  [19  8]
  [16  8]]

 [[ 5  8]
  [ 2 13]
  [ 9  8]
  [ 7 12]
  [ 5  1]
  [ 1  9]
  [ 8 11]]

 [[11  1]
  [ 9 12]
  [14 12]
  [ 5  6]
  [16 12]
  [12 13]
  [ 2 19]]

 [[ 4 17]
  [ 7  4]
  [19  2]
  [ 5 15]
  [ 7 14]
  [18 12]
  [ 6 16]]]
